### ISSUE TITLE
Panda Builder Roadmap

### ISSUE THREAD

**Issue by dyoder** [pandastrike/panda-builder#5]
- [ ] Multi-update support: `update:package`.
- [ ] Switch CLI to `builder` from Gulp.
- [ ] Dependency verification: `update:audit`,
- [ ] Multi-repo management: `update:dependencies`.
- [ ] Convenience tasks: `update:all` and `update`.

------

## Introduction

Our initial experiments with Panda Builder have been a success. We now use the tool on a half-dozen packages and the list is growing. We want to be able to support additional scenarios. These include:

- Updates to the build process, like targeting more recent versions of Node.
- Updates to the modules we use in the build process, like the version of CoffeeScript.
- New features in the build process, such as adding new targets.
- Updating groups of related packages all at once.

### What About Mono-Repos?

We could solve a number of these problems by using a tool like Lerna to manage builds. This makes sense when you have what amounts to a single project that has lots of modules that you might want to make available independently. For example, suppose we were to break up Panda River into individual functions so that you could import only the functions you want, thus reducing bandwidth requirements. In that case, having a mono-repo might be appealing.[^1]

[^1]: Even then, it's not clear that it wouldn't be easier to automate that by _generating_ `package.json` files for each package. But that's a different discussion. Suffice to say Dan is known as the AntiLerna.

However, in most cases, we do want to maintain the independence of the individual repositories. Most of the complexity in Panda Builder is related to the actual build process, not managing repos. And updates are relatively simple to handle. The most recent update involves about forty lines of CoffeeScript. And managing multiple repos is [borderline trivial](#multi-repo-management).

Combining repos also has the drawback of combining their tickets, release management, and other tooling typically built around Git. We want to leverage that tooing unless we're simply making a single module available in a more granular (bandwidth-friendly) manner.

## Multi-Update Support

Updates are pretty simple. They consist of updating project files, primarly `package.json`, and that primarily to update dependencies, but sometimes we want to update a license file or `.gitignore` or something like that.

We can check `package.json` to see which version of Builder is presently installed. We keep that in memory and update Builder. We can compare versions to determine which updates to run. For example, if we started at `2.3.3` and the newly updated version is `3.0.0` we know we want to run all the updates after `2.3.3`.

Assuming we keep the updates in Builder like this:

```
src/
  updates/
    2.3.4.coffee
    2.3.5.coffee
    3.0.0.coffee
```

we can get a sorted list of the updates and compare them to the prior and current versions to select only the updates we want to run. We simply run them in order.

The output for that might look something like this:

```
Panda Builder update ...
Starting update for 2.3.4 ...
Updating dependencies ...
Updating files ...
Update for 2.3.4 done.
Starting update for 2.3.5 ...
```

and so on.

### Version Bumps

If an update is minor, like fixing a build bug, we can bump the patch. Otherwise we can bump either the minor or even major version. But we don't want to accidentally go from, say, `3.1` to `7.0` in the process. Instead, each update should keep track of the highest level of bump (patch, minor, major) encountered so far, and the higher level update manager is ultimately the one that does the bump.

## Switch To `builder` CLI

If we install a general CLI, we can do away with the `init` command. Instead, `builder update` will be able to handle it via the multi-update support, since the init stuff will just be the `1.0.0` update. In addition, that will make it possible to switch later to P9K without having to worry about changing the commands.

## Dependency Verification

We can use the [NPM CLI](https://docs.npmjs.com/cli/view) to check each dependency to see if it includes Builder as a dependency. We pull these dependencies, check each with NPM to see if Builder is a dependency of that dependency, see if the version is current, and exit with an error if it isn't. For example, if you attempt to update River without updating Garden first, it might look like this:

```
$ npx builder update
Panda Builder update ...
Starting update for 2.3.4 ...
Checking dependencies...
Fatal error: one or more dependencies need updating.
- `panda-garden` is using panda-builder 2.3.3.
- `panda-generics` is using panda-builder 2.3.2
Please run `builder update` within each of these projects
and try again.
```

This is nice incremental improvement and lays the foundation for multi-repo management.

## Multi-Repo Management

Consider the following shell script:

```bash
for repo in panda-garden panda-generic panda-parchment panda-river;
  if [[ -d  ${repo} ]]; then
    (cd ${repo} && builder update)
  fi
done
```

That's essentially we need to automate simultaneous updates. If we add a command to generate that list for a given repo, say `builder audit`, the script becomes:

```bash
for repo in $(builder audit);
  if [[ -d  ../${repo} ]]; then
    (cd ${repo} && builder update)
  fi
done
```

We could port this into CoffeeScript and add some error handling, and call this `update:dependencies`. That's how easy the multi-repo problem is to handle.

We can't update _all_ the packages using Builder this way, but I don't think that's necessary. Any dependency tree can be handled and that's all we need.

## Summary Of New Tasks

Each of the following would be executed as `builder update:<task>`.

### package

- Update package.
- Apply updates.
- Bump version.

### audit

- Verify dependencies.

### dependencies

- Verify dependences and update.
- Operates recursively.
- Depends on packages being locally installed already.
- We could eventually auto-clone if they're not present.

### all

- Convenience for `builder update:dependencies update:package`
- Does not publish or tag anything.

If you want to also publish and tag, you can simply add those tasks:

```
builder update:all publish git:tag
```

To make this even easier `builder update` will do all three.
